# docker compose up --detach --build --force-recreate --remove-orphans
services:
  web:
    image: eventnet/web
    container_name: eventnet_web
    restart: always
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Context=Host=eventnet_database;Port=5432;Database=postgres;Username=postgres;Password=masterpassword;
    depends_on:
      - database
    ports:
      - 8090:8080
  database:
    image: postgres
    container_name: eventnet_database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
